services:
  postgres-master:
    image: citusdata/citus:13.0.3
    environment:
      NODE_ROLE: master
      POSTGRES_PASSWORD: postgres
    deploy:
      placement:
        constraints:
          - node.role == manager

  postgres-worker:
    image: citusdata/citus:13.0.3
    environment:
      NODE_ROLE: worker
      POSTGRES_PASSWORD: postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - postgres-master
  php:
    image: registry.kiora.tech/kiora/kiora-crm_php:0.0.2
    user: "www-data"
    depends_on:
      - postgres-master
    environment:
      - APP_ENV=prod
      - DATABASE_URL=pgsql://postgres:postgres@postgres-master:5432/postgres
      - MAILER_DSN=${MAILER_DSN:-smtp://mailer:1025}
    restart:
      always
  nginx:
    image: registry.kiora.tech/kiora/kiora-crm_nginx:0.0.2
    depends_on:
      - php
      - postgres-master
    restart:
      always

